version: "3"

services:
  postgres:
    image: "openmaptiles/postgis:2.9"
    ports:
      - 54325:5432
    env_file: docker/.env

  importer:
    image: openmaptiles/import-osm
    env_file: docker/.env
    volumes:
     - ./docker/imposm/import:/import
     - ./settings/imposm_import.yml:/mapping/mapping.yaml
     - ./settings/post-process-internal.sql:/mapping/post-process-internal.sql
     - ./settings/post-process-display.sql:/mapping/post-process-display.sql
     - ./settings/post-process-api.sql:/mapping/post-process-api.sql
     - ./settings/run_importer.sh:/mapping/run_importer.sh
     - ./settings/api:/mapping/api
    depends_on:
      - postgres
    entrypoint: /bin/bash
    command: "/mapping/run_importer.sh"

  t-rex:
    image: sourcepole/t-rex
    volumes:
      - ./settings/trex.toml:/config/config.toml
      - ./docker/trex_cache:/srv/mvtcache
    depends_on:
      - postgres
    ports:
      - 6767:6767
    entrypoint: /usr/bin/t_rex serve -c /config/config.toml

  web:
    image: httpd:2.4
    volumes:
     - ./web/:/usr/local/apache2/htdocs/
    depends_on:
      - t-rex
    ports:
      - 8082:80
